

apiVersion: v1
kind: Service
metadata:
  #  namespace: default
  name: xxl-job
  labels:
    app: xxl-job
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 6210
      name: web
  selector:
    app: xxl-job