

apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: sentinel
  labels:
    app: sentinel
spec:
  type: NodePort
  ports:
    - port: 8280
      targetPort: 8280
      nodePort: 8280
      name: web
    - port: 8719
      targetPort: 8719
      nodePort: 8719
      name: api
  selector:
    app: sentinel

