

apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: logstash
  labels:
    app: logstash
spec:
  type: NodePort
  ports:
    - port: 5621
      targetPort: 5621
      nodePort: 5621
  selector:
    app: logstash